controller_list:
  - name: "movo/right_arm_controller"
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
     - right_shoulder_pan_joint
     - right_shoulder_lift_joint
     - right_arm_half_joint
     - right_elbow_joint
     - right_wrist_spherical_1_joint
     - right_wrist_spherical_2_joint
     - right_wrist_3_joint
